#!/usr/bin/env sh

dir="/etc/void"
. "${dir}/fun.sh"
. "${dir}/cfg.sh"

# create bridge with uplink and self vlan
add_ubr "${br}" "${uplink_dev}" "${br_self_vlan}" || exit 1
uplink_vlans add "${uplink_dev}" "${vlans}" || exit 1
sleep infinity
