#!/usr/bin/env sh

srv=$(basename ${PWD})
scut() { echo ${srv} | cut -d '_' -f${1}; };

bridge=$(scut 2);     test ${bridge} = ${srv} && bridge="out" && srv="${srv}_out"
max_vlan=$(scut 3);   test -z ${max_vlan}     && max_vlan=250
max_tt=$(scut 4);     test -z ${max_tt}       && max_tt=2
user=$(scut 5);       test -z ${user}         && user=user
mac_prefix=$(scut 6); test -z ${mac_prefix}   && mac_prefix="aabb0"

ip -br link show ${bridge} || exit 1

for v in $(seq ${max_vlan}); do
 for i in $(seq ${max_tt}); do
  tt="${bridge}_v${v}_i${i}"
  ip tuntap add name ${tt} mode tap user ${user}
  vlan_hex=$(echo 00$(echo "obase=16;${v}" | bc) | tail -c 4)
  int_hex=$(echo 0$(echo "obase=16;${i}" | bc) | tail -c 3)
  mac=$(echo "${mac_prefix}${vlan_hex}0f${int_hex}" | sed 's/../:&/2g' | tr [A-Z] [a-z])
  ip link set ${tt} address ${mac}
  ip link set ${tt} up
  ip link set ${tt} master ${bridge}
  bridge vlan del dev ${tt} vid 1
  bridge vlan add dev ${tt} vid ${v} pvid untagged master
  bridge vlan add dev ${bridge} vid ${v} master
 done
done

sleep infinity
